### ISSUE TITLE
Endless Terrain

### ISSUE THREAD

**Issue by zaBogdan** [SebLague/Procedural-Landmass-Generation#14]
Hello. 

Can you say me how to disable EndlessTerrrain script? Because I really don't need it. I just want to use the FallOffMap.

Thanks!

**Comment by LittleWhite-tb** [comment]
Hello,

Technically, the FallOffMap script is independent of everything else. You can create an empty project, import the script and voilà, you can generate the falloff map (by calling GenerateFalloffMap()).
I guess, you need to be more precise in your question in order to receive more precise help.
