### ISSUE TITLE
Seams not matching up

### ISSUE THREAD

**Issue by sboigelot** [SebLague/Procedural-Landmass-Generation#3]
Hello @SebLague 

First of all, thanks for you tutorial, it is great!

When trying your endless terrain, I still have issue with seams not matching, even between different terrain chunck of the same LOD.

Am I forgetting to configure a setting?

![image](https://cloud.githubusercontent.com/assets/6545998/18883373/440dce12-84e3-11e6-9a83-63f29d07fb1f.png)

The normalize mode is set to Global.

![image](https://cloud.githubusercontent.com/assets/6545998/18883407/56f1e130-84e3-11e6-8897-ba60d1b0dcb3.png)
![image](https://cloud.githubusercontent.com/assets/6545998/18883417/638c87c4-84e3-11e6-90cb-a8eb53013728.png)

**Comment by JustinSchneider** [comment]
I'm having this issue, too. Even after the E10 Seams resolutions. It was working fine for a while, but something we changed along the way broke seams again.

Once I catch up on the series, I'll investigate and see if I can get to the root of the problem. I'll report back on anything I find.

**Comment by JustinSchneider** [comment]
@sboigelot Because I wanted flatshading more than the texture-based elements from the latest episodes, I rolled my code back to the equivalent of the end of Episode 15. I then went about undoing the changes made at the end of that episode, like removing the colorMap usage. I compartmentalized things using the new data structures, and I now have both flatshading and the seams sorted out again.

My suspicion is that the seam issue had something to do with the changes made inside MapGenerator's GenerateMapData method. I didn't have time last night to really look through it, but I'd recommend starting there.

**Comment by sboigelot** [comment]
Thanks a lot for the update, I will have a look at your changes. I was experiencing exactly the same seams issue with my own code and can't understand it as I'm not a 3d mesh generation expert :)

I hope looking at your newest code will help me understand the issue better.

**Comment by sboigelot** [comment]
Your last episode clear this issue, thanks for the awesome work and tutorial
